### ISSUE TITLE
Does this use dpring.json?

### ISSUE THREAD

**Issue by linonetwo** [so1ve/eslint-plugin-dprint-integration#10]
This is my config with `preferSingle`

```json
{
  "lineWidth": 140,
  "typescript": {
    "quoteStyle": "preferSingle",
    "binaryExpression.operatorPosition": "sameLine"
  },
  "json": {
  },
  "markdown": {
  },
  "includes": ["**/*.{ts,tsx,js,jsx,cjs,mjs,json,md}"],
  "excludes": [
    "**/node_modules",
    "**/*-lock.json"
  ],
  "plugins": [
    "https://plugins.dprint.dev/typescript-0.84.1.wasm",
    "https://plugins.dprint.dev/json-0.17.1.wasm",
    "https://plugins.dprint.dev/markdown-0.15.2.wasm"
  ]
}

```

But

![截屏2023-04-12 22 16 57](https://user-images.githubusercontent.com/3746270/231486128-432b9916-3b59-4155-84c1-71fd73766680.png)

**Comment by so1ve** [comment]
Yes, because dprint cli supports "extends" and if you want to use dprint.json, it is hard to resolve the relative path? let me check :)

**Comment by so1ve** [comment]
> Thanks, you worth a new follower.

Thanks!! Following you too :)
[v0.2.0](https://github.com/so1ve/eslint-plugin-dprint-integration/releases/tag/v0.2.0) is released (I merged the pr incorrectly so the commit messages are messed up...)
