### ISSUE TITLE
Turn off linter rules

### ISSUE THREAD

**Issue by linonetwo** [so1ve/eslint-plugin-dprint-integration#11]
https://typescript-eslint.io/linting/troubleshooting/formatting/

> Note that even if you use a formatter other than prettier, you can use eslint-config-prettier as it exclusively turns off all formatting rules.

Now I have to keep prettier config.

**Comment by so1ve** [comment]
Ah, the rules are included in this plugin. Not mentioned in the doc. Sorry :(
